---
# todo: create roles / playbooks and tasks with appropriate become method
# todo: create environment that allows webadmins to administer wordpress instead of root
# done: generate cnf file based on generated password
# todo mysql_secure_installation / harden mysql
# stupid ansible agentless hype: mysql-python package needed to let mysql_user work :-(
# done: look for reloading service: fixed by defining handler
# done: make wp password secret. use stdout method
- hosts: ansclient
  become: true
  become_user: root
  roles:
    - role: tob.wordpress
      wp_db_name: wp_test2234
      wp_domain: wordpress2.appelo.org
      
#  tasks:
#          - name: install wordpress site
#            command: "/usr/local/bin/wp --path=/var/www/html/wordpress2.appelo.org/ core install --url {{wp_domain}} --title {{wp_domain}} --admin_email asdf@xs.com"
